### ISSUE TITLE
Api version is not compatible

### ISSUE THREAD

**Issue by Florian-Wegner** [AlEscher/EasyAvatar#1]
Plugin could not be loaded: Api version is not compatible: 24 (minimum: 26, current: 26)

Please update <3

**Comment by AlEscher** [comment]
Hi @Florian-Wegner ,
I updated the plugin to version 26, the new version is available under release 1.3: https://github.com/AlEscher/EasyAvatar/releases/tag/v1.3

**Comment by Florian-Wegner** [comment]
It now works wonderfully, thank you very much
